# ========================================
# Main configuration file
# ========================================
server:
  port: 8080

spring:
  main:
    banner-mode: off
  profiles:
    active: @active.profile@

app:
  mdc:
    current-user-key: currentUser
    request-timestamp-key: requestTimestamp

